# Generated by Django 4.0.10 on 2023-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overview', models.CharField(max_length=50, unique=True)),
                ('requirements', models.CharField(max_length=50, unique=True)),
                ('skills_you_will_learn', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('MECHANICS & ENGINEERING', 'MECHANICS & ENGINEERING'), ('SCIENCE & MEDICINE', 'SCIENCE & MEDICINE'), ('SIGNAL & INTELLIGENCE', 'SIGNAL & INTELLIGENCE'), ('SUPPORT & LOGISTICS', 'SUPPORT & LOGISTICS'), ('GROUND FORCES', 'GROUND FORCES'), ('AVIATION & AERIAL DEFENCE', 'AVIATION & AERIAL DEFENCE'), ('NAVY FORCES', 'NAVY FORCES')], max_length=100)),
                ('only_for_soldiers', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('applicant_email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('reason_for_application', models.CharField(max_length=500)),
                ('recruiter_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
