# Generated by Django 4.0.10 on 2023-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforce',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='overview',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='requirements',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='skills_you_will_learn',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
